# go build -o ./target/server main.go
# go build -o ./target/chitchat/chitchat ./ChitChat/*.go
# go build -o ./target/c3/handle ./c3/handle/*.go
# go build -o ./target/c3/handlefunc ./c3/handlefunc/*.go
# go build -o ./target/c3/chain_handlefunc ./c3/chain_handlefunc/*.go
# go build -o ./target/c3/chain_handler ./c3/chain_handler/*.go
# go build -o ./target/c3/httprouter ./c3/httprouter/*.go
# go build -o ./target/c3/https ./c3/https/*.go
# go build -o ./target/c4/header ./c4/header/*.go
# go build -o ./target/c4/body ./c4/body/*.go
# go build -o ./target/c4/form ./c4/form/*.go
# go build -o ./target/c4/file_upload ./c4/file_upload/*.go
# go build -o ./target/c4/write ./c4/write/*.go
# go build -o ./target/c4/cookie ./c4/cookie/*.go
# go build -o ./target/c5/simple_template/ ./c5/simple_template/*.go
# go build -o ./target/c5/random_number/ ./c5/random_number/*.go
# go build -o ./target/c5/iterator/ ./c5/iterator/*.go
# go build -o ./target/c5/set_dot/ ./c5/set_dot/*.go
# go build -o ./target/c5/include/ ./c5/include/*.go
# go build -o ./target/c5/custom/ ./c5/custom_function/*.go
# go build -o ./target/c6/map_store/ ./c6/map_store/*.go
# go build -o ./target/c6/read_write_files/ ./c6/read_write_files/*.go
# go build -o ./target/c6/csv_store/ ./c6/csv_store/*.go
# go build -o ./target/c6/gob_store/ ./c6/gob_store/*.go
# go build -o ./target/c6/sql_store1/ ./c6/sql_store1/*.go
# go build -o ./target/c6/sql_store2/ ./c6/sql_store2/*.go
# go build -o ./target/c6/sqlx/ ./c6/sqlx/*.go
# go build -o ./target/c6/gorm/ ./c6/gorm/*.go
# go build -o ./target/c7/xml_parsing_unmarshal_1/ ./c7/xml_parsing_unmarshal_1/*.go
# go build -o ./target/c7/xml_parsing_unmarshal_2/ ./c7/xml_parsing_unmarshal_2/*.go
# go build -o ./target/c7/xml_parsing_decoder/ ./c7/xml_parsing_decoder/*.go
# go build -o ./target/c7/xml_creating_marshal/ ./c7/xml_creating_marshal/*.go
# go build -o ./target/c7/xml_creating_encoder/ ./c7/xml_creating_encoder/*.go
# go build -o ./target/c7/json_parsing_unmarshal/ ./c7/json_parsing_unmarshal/*.go
# go build -o ./target/c7/json_parsing_decoder/ ./c7/json_parsing_decoder/*.go
# go build -o ./target/c7/json_creating_marshal/ ./c7/json_creating_marshal/*.go
# go build -o ./target/c7/json_creating_encoder/ ./c7/json_creating_encoder/*.go
# go build -o ./target/c7/web_service/ ./c7/web_service/*.go
go build -o ./target/c9/wait_group/ ./c9/wait_group/*.go
