# go build -o ./target/server main.go
# go build -o ./target/chitchat/chitchat ./ChitChat/*.go
# go build -o ./target/c3/handle ./c3/handle/*.go
# go build -o ./target/c3/handlefunc ./c3/handlefunc/*.go
# go build -o ./target/c3/chain_handlefunc ./c3/chain_handlefunc/*.go
# go build -o ./target/c3/chain_handler ./c3/chain_handler/*.go
# go build -o ./target/c3/httprouter ./c3/httprouter/*.go
# go build -o ./target/c3/https ./c3/https/*.go
# go build -o ./target/c4/header ./c4/header/*.go
# go build -o ./target/c4/body ./c4/body/*.go
# go build -o ./target/c4/form ./c4/form/*.go
# go build -o ./target/c4/file_upload ./c4/file_upload/*.go
# go build -o ./target/c4/write ./c4/write/*.go
# go build -o ./target/c4/cookie ./c4/cookie/*.go
# go build -o ./target/c5/simple_template/ ./c5/simple_template/*.go
# go build -o ./target/c5/random_number/ ./c5/random_number/*.go
# go build -o ./target/c5/iterator/ ./c5/iterator/*.go
# go build -o ./target/c5/set_dot/ ./c5/set_dot/*.go
go build -o ./target/c5/include/ ./c5/include/*.go